# Generated by Django 3.1.4 on 2020-12-22 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hammadde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hammadde_ad', models.CharField(max_length=30)),
                ('temin_sure', models.DateField()),
                ('stok_adet', models.IntegerField()),
                ('fiyat', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Hammadde',
                'verbose_name_plural': 'Hammaddeler',
            },
        ),
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_adi', models.CharField(blank=True, max_length=100)),
                ('urun_aciklama', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('ebat', models.CharField(blank=True, max_length=100)),
                ('fiyat', models.IntegerField()),
                ('fiyat_oran', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
            },
        ),
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adet', models.IntegerField()),
                ('tarih', models.DateTimeField()),
                ('bayi', models.ForeignKey(limit_choices_to={'groups__name': 'BayiGrubu'}, on_delete=django.db.models.deletion.CASCADE, related_name='bayi', to=settings.AUTH_USER_MODEL, verbose_name='bayi')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lift.urun')),
            ],
            options={
                'verbose_name': 'Bayi Sipariş',
                'verbose_name_plural': 'Bayi Siparişleri',
            },
        ),
        migrations.CreateModel(
            name='Recete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adet', models.IntegerField()),
                ('hammadde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lift.hammadde')),
                ('urunler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lift.urun')),
            ],
            options={
                'verbose_name': 'Reçete',
                'verbose_name_plural': 'Reçeteler',
            },
        ),
        migrations.CreateModel(
            name='Odeme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odeme_turu', models.CharField(max_length=100)),
                ('bayiler_siparis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lift.siparis')),
            ],
            options={
                'verbose_name': 'Bayi Ödeme',
                'verbose_name_plural': 'Bayi Ödemeleri',
            },
        ),
        migrations.CreateModel(
            name='Bakim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem_turu', models.CharField(max_length=30)),
                ('maliyet', models.IntegerField()),
                ('sure', models.DateField()),
                ('urunler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lift.urun')),
            ],
            options={
                'verbose_name': 'Bakım',
                'verbose_name_plural': 'Bakımlar',
            },
        ),
    ]
