# Generated by Django 3.1.4 on 2020-12-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recete',
            name='char',
            field=models.CharField(default='sa', max_length=50),
            preserve_default=False,
        ),
    ]
