# Generated by Django 3.1.4 on 2021-01-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='urun_resim',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
