# Generated by Django 3.1.4 on 2021-01-02 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lift', '0002_urun_urun_resim'),
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslık', models.CharField(blank=True, max_length=50)),
                ('resim', models.ImageField(blank=True, upload_to='images/')),
                ('urunler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lift.urun')),
            ],
        ),
    ]
