# Generated by Django 3.1.4 on 2021-01-02 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lift', '0003_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='baslık',
            new_name='baslik',
        ),
    ]
