# Generated by Django 3.1.4 on 2021-01-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lift', '0004_auto_20210102_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='siparis',
            name='status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
