# Generated by Django 3.1.4 on 2021-01-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lift', '0005_siparis_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siparis',
            name='status',
        ),
        migrations.AddField(
            model_name='siparis',
            name='STATUS',
            field=models.CharField(choices=[('0', 'yeni'), ('1', 'ödendi'), ('2', 'hazırlanma'), ('3', 'tamamlandı')], default=1, max_length=4),
            preserve_default=False,
        ),
    ]
