# Generated by Django 3.1.4 on 2021-01-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lift', '0006_auto_20210109_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='stok',
            field=models.IntegerField(blank=True, default=200),
            preserve_default=False,
        ),
    ]
