# Generated by Django 3.1.3 on 2021-01-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lift', '0007_urun_stok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparis',
            name='STATUS',
            field=models.CharField(choices=[('0', 'sepette'), ('1', 'hazırlanıyor'), ('2', 'ödendi'), ('3', 'tamamlandı')], max_length=4),
        ),
    ]
