# Generated by Django 3.1.3 on 2021-01-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lift', '0008_auto_20210115_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urun',
            name='fiyat_oran',
        ),
        migrations.AddField(
            model_name='siparis',
            name='fiyat_oran',
            field=models.IntegerField(blank=True, default=12),
            preserve_default=False,
        ),
    ]
