# Generated by Django 3.1.3 on 2021-01-15 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bayi_bilgi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(max_length=100)),
                ('adres', models.TextField()),
                ('resim', models.ImageField(blank=True, upload_to='images/')),
                ('bayis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bayis', to=settings.AUTH_USER_MODEL, verbose_name='bayis')),
            ],
        ),
    ]
