# Generated by Django 3.1.3 on 2020-12-19 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bayiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bayi_ad', models.CharField(max_length=30)),
                ('bayi_adres', models.CharField(max_length=50)),
                ('bayi_tel', models.CharField(max_length=30)),
                ('bayi_mail', models.CharField(max_length=30)),
                ('sifre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ebat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebat_ad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hammadde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hammadde_ad', models.CharField(max_length=30)),
                ('temin_sure', models.TimeField()),
                ('stok_adet', models.IntegerField()),
                ('fiyat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Modeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_ad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Urunler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_ad', models.CharField(max_length=50)),
                ('fiyat', models.IntegerField()),
                ('status', models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], max_length=10)),
                ('slug', models.SlugField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('ebat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bayi.ebat')),
            ],
        ),
        migrations.CreateModel(
            name='Recete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanim', models.CharField(max_length=50)),
                ('hammadde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bayi.hammadde')),
                ('urunler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bayi.urunler')),
            ],
        ),
        migrations.CreateModel(
            name='Bayiler_Siparis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adet', models.IntegerField()),
                ('tarih', models.DateTimeField()),
                ('bayiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bayi.bayiler')),
            ],
        ),
        migrations.CreateModel(
            name='Bayiler_Odeme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odeme_turu', models.CharField(max_length=30)),
                ('bayiler_siparis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bayi.bayiler_siparis')),
            ],
        ),
        migrations.CreateModel(
            name='Bakim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem_turu', models.CharField(max_length=30)),
                ('maliyet', models.IntegerField()),
                ('sure', models.TimeField()),
                ('urunler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bayi.urunler')),
            ],
        ),
    ]
