# Generated by Django 3.1.4 on 2021-01-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bayi_bilgi',
            name='resim',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
