# Generated by Django 3.1.3 on 2020-12-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayi', '0002_auto_20201220_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunler',
            name='status',
            field=models.BooleanField(),
        ),
    ]
